# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [17]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
#Method 1
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
#Method 2
np.array([0]*10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Create an array of 10 ones

In [5]:
#Method 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#Method 2
np.array([1]*10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [7]:
#Method 1
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [8]:
#Method 2
np.array([5]*10)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [9]:
#Method 1
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [10]:
#Method 2
np.array(range(10,51))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [11]:
#Method 1
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [18]:
#Method 2
np.array(range(10,50,2))

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [14]:
#Method 1
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#Method 2
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [19]:
#Method 1
np.random.rand()

0.41082041610637043

In [20]:
#Method 2
np.random.rand(1)

array([0.89295912])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [21]:
np.random.randn(25)

array([-0.53850106, -0.43007425, -1.64984044, -0.49511243, -0.50179719,
        0.6304249 , -0.12123323,  1.21737496, -0.49779264, -0.71646054,
        0.04089609, -1.66219452,  2.29262541, -0.35428189, -0.27785429,
        0.67789414,  0.58803352, -1.17585766,  1.14128336,  0.25322912,
       -0.31057591,  0.04354104,  0.46300313, -1.65822422,  1.30123892])

#### Create the following matrix:

In [27]:
np.random.rand(100).reshape(10,10)

array([[0.76646757, 0.86308783, 0.13977235, 0.05198249, 0.6991649 ,
        0.12052757, 0.08696885, 0.19649887, 0.92135153, 0.09477661],
       [0.49668865, 0.02109565, 0.40742277, 0.47434109, 0.81134411,
        0.28989957, 0.92886049, 0.70477644, 0.35315092, 0.23386   ],
       [0.1196296 , 0.33653754, 0.22986147, 0.30168044, 0.89567661,
        0.66264412, 0.69447962, 0.20183586, 0.76199282, 0.88449967],
       [0.36225845, 0.40512375, 0.93371664, 0.61872149, 0.68084551,
        0.13881282, 0.3790666 , 0.15701049, 0.06097917, 0.36378049],
       [0.47244085, 0.12201303, 0.4026567 , 0.92456832, 0.17836788,
        0.99088102, 0.06110182, 0.83103106, 0.61804446, 0.20971315],
       [0.31459313, 0.20913056, 0.82367975, 0.15143511, 0.81813421,
        0.1153921 , 0.02623427, 0.16112088, 0.56104654, 0.99005039],
       [0.7419082 , 0.49326724, 0.70347246, 0.59599893, 0.28912183,
        0.46925808, 0.34195056, 0.55681806, 0.22706331, 0.47921356],
       [0.95561519, 0.24510512, 0.0949104

#### Create an array of 20 linearly spaced points between 0 and 1:

In [28]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [31]:
#Method 1
mat[3,4]

20

In [32]:
#Method 2
mat[3][4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [33]:
#Method 1
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [35]:
#Method 2
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [36]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [38]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [39]:
#Method 1
mat.sum()

325

In [40]:
#Method 2
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [41]:
#Method 1
mat.std()

7.211102550927978

In [42]:
#Method 2
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [43]:
#Method 1
mat.sum(0)

array([55, 60, 65, 70, 75])

In [44]:
#Method 2
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])